#!/usr/bin/env php
<?php

$base_dir = __DIR__;

require_once( "$base_dir/lib/Observe.php" );
require_once( "$base_dir/lib/myCurl.php" );

$options = getopt("u:", array("rdf"));

$plugins = CensusPluginRegister::instance();
$plugins->loadDir( "$base_dir/plugins.d" );

$domains = array(
	"totl.net",
	"ecs.soton.ac.uk",
	"eprints.org",
	"microsoft.com" );

foreach( file( "unis.urls" ) as $line )
{
	$domains []= trim( $line );
}

if(array_key_exists("u",$options))
{
	$domains = array($options["u"]);
}

$rdfout = array_key_exists("rdf", $options);
if( $rdfout )
{
	require_once( "$base_dir/lib/arc2/ARC2.php" );
	require_once( "$base_dir/lib/Graphite/Graphite.php" ); #only used for RDF output.
}

$ttl = 10;	
foreach( $domains as $domain )
{
	$url = "http://$domain/";
		
	$curl = new mycurl( true, 10, 10 );
	$curl->createCurl( $url );

	$result = $plugins->applyTo( $curl );

	print "\n$domain:\n";
	print json_encode($result );
	print "\n";

	if($rdfout)
	{
		$graph = new Graphite();
		$graph->ns( "obsacuk", "http://observatory.data.ac.uk/vocab#" );
		$plugins->resultsToGraph( $graph, $result, $domain, date("c") );
		print $graph->serialize("NTriples");
	}
}



